// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmVl3hekJjGzoLuhnjPrFJSvS9XqjSYK0',
    appId: '1:215392438772:web:c8b3f81350dce09c97d1a1',
    messagingSenderId: '215392438772',
    projectId: 'expense-tracker-f2e6e',
    authDomain: 'expense-tracker-f2e6e.firebaseapp.com',
    storageBucket: 'expense-tracker-f2e6e.firebasestorage.app',
    measurementId: 'G-W56LCHTHBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02PyKYubAEEqdeCVPXfBmAJWhCKVDWG8',
    appId: '1:215392438772:android:2dd1f9435055c3e697d1a1',
    messagingSenderId: '215392438772',
    projectId: 'expense-tracker-f2e6e',
    storageBucket: 'expense-tracker-f2e6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ0BQwD1Nwj-peARAu6_aaGwavvo1uQhs',
    appId: '1:215392438772:ios:47717ded7968900d97d1a1',
    messagingSenderId: '215392438772',
    projectId: 'expense-tracker-f2e6e',
    storageBucket: 'expense-tracker-f2e6e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ0BQwD1Nwj-peARAu6_aaGwavvo1uQhs',
    appId: '1:215392438772:ios:47717ded7968900d97d1a1',
    messagingSenderId: '215392438772',
    projectId: 'expense-tracker-f2e6e',
    storageBucket: 'expense-tracker-f2e6e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmVl3hekJjGzoLuhnjPrFJSvS9XqjSYK0',
    appId: '1:215392438772:web:f88256185427f4ce97d1a1',
    messagingSenderId: '215392438772',
    projectId: 'expense-tracker-f2e6e',
    authDomain: 'expense-tracker-f2e6e.firebaseapp.com',
    storageBucket: 'expense-tracker-f2e6e.firebasestorage.app',
    measurementId: 'G-QY91E5R5SE',
  );
}
